### PR TITLE
UI stuff

### PR DESCRIPTION
**Pull request by mfriesen1024**

### CODE REVIEW

**Comment by mfriesen1024** [comment]
@Zyganadel I need sprites for ui. it dont like boxes.

**Comment by mfriesen1024** [comment]
HP and Shields need sprites and some sort of box to make pretty.

**Comment by Zyganadel** [comment]
> @Zyganadel I need sprites for ui. it dont like boxes.

Later. Adding as issue and will add in a later patch.

**Review by Zyganadel — APPROVED** [review]
Good for now.

**Pull request merged**
